### ISSUE TITLE
Dropwizard bundles with @inject on constructors dont work

### ISSUE THREAD

**Issue by archanmishra** [xvik/dropwizard-guicey-examples#1]
Hi,

We are migrating from dropwizard 0.9 to 1.1 and from hubspot.dropwizard-guice to guicey.

Previously bundles with @inject on them would work, but now we get Injector not initialised error.

This was not the issue with dropwizard-guice. Any recommendations on why this happened and a example which deals with the same scenario.

**Comment by xvik** [comment]
Hi!

Dropwizard-guice was initially creating guice injector at configuration phase and now they moved creation to runtime phase. Probably you were using a too old version with that legacy behavior and so be able to use injections on bundles. 

Talking generally, it is very weird to use injection on bundles: bundles belong to configuration phase and should be used only for configuration of future runtime (including guice). It will never be possible in guicey to use injection during application configuration (only in application run method).

You can describe me your case and will try to suggest a better way.

**Comment by archanmishra** [comment]
My case is to attach a Filter class to environment jersey in run method of bundle.
This filter class is injected at constructor.
```java
public class XkcdBundle implements Bundle{

  private final GuiceBundle bundle;

 @Inject
  public XkcdBundle(Provider<ClientFilter> clientFilterProvider) {
    this.clientFilterProvider = clientFilterProvider;
 }

  @Override
  public void initialize(Bootstrap<?> bootstrap) {

  }

  @Override
  public void run(Environment environment) {
   environment.jersey().register(clientFilterProvider.get());
  }
}
```

Hence the need of injection. Can you suggest a alternative approach. 

ps. many thanks for quick response.

**Comment by xvik** [comment]
Guicey uses extensions with installers concept. You tell it extension classes and registered installers must recognize extension and register properly `GuiceBundle.builder().extensions(Ext1.class).build()`).
Extensions are implicitly registered as guice beans and installers register extension instance, obtained from guice context.

Dropwizard bundles are not suitable for extensions registration, so guicey have to introduce its own GuiceyBundle: `GuiceBundle.builder().bundles(new MyGuiceyBundle()).build()` which can register extensions (`bootstrap.extensions(Ext1.class)`)

If I'm right then you were using ClientFilter from jersey 1 and now you will use ContainerRequestFilter or ContainerResponseFilter. If so, then [jersey provider installer](http://xvik.github.io/dropwizard-guicey/4.1.0/installers/jersey-ext/#containerrequestfilter) will handle installation and you only need to register filter classes.

Complete sample:

```java
class MyBundle implements GuiceyBundle {
     void initialize(GuiceyBootstrap bootstrap) {
          bootstrap.extensions(MyFilter1.class, MyFilter2.class);
     }
}

GuiceBundle.builder().bundles(new MyBundle()).build()
```

**Comment by archanmishra** [comment]
Hi resolved the issue by adding @Provider on top of the client filter.
We were already using the container filters.

**Comment by xvik** [comment]
Yes, I forgot to mention @Provider.  
Closing issue as problem solved.
