### ISSUE TITLE
Question: Compatibility with Java 11+ (illegal reflective access)

### ISSUE THREAD

**Issue by mumeraltaf** [xvik/dropwizard-guicey-examples#19]
Hi,

I am not sure if I should ask it on the main dropwizard-guicey repository or here, but one of the examples here help demonstrate the issue.
The Jdbi3Application throws the illegal reflective access warning/error when used with Java 11 or higher:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by javassist.util.proxy.SecurityActions (file:/Users/.../.gradle/caches/modules-2/files-2.1/org.javassist/javassist/3.27.0-GA/f63e6aa899e15eca8fdaa402a79af4c417252213/javassist-3.27.0-GA.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of javassist.util.proxy.SecurityActions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

This happens with any Dropwizard project using this extension, my initial research shows that Java 11 gives this warning and later Java versions throw error. This has to do with updated java API for generating classes, used by javassist.

Other packages (like Dropwizard core itself), have addressed this issue by moving to newer API (see [Dropwizard issue: 2962](https://github.com/dropwizard/dropwizard/issues/2962))

My query is that is this a requirement for you to stay with Java 11 and lower for now? Or are there plans to adopt the newer API?

I totally understand if moving to newer API does not aligns with current project goals.

**Comment by xvik** [comment]
Hi!

Thank you for the link! As I can see there is a way to keep java 8 compatibility, so it should be possible to fix this.
I'll look (maybe not very soon, but will do).

**Comment by xvik** [comment]
The issue was fixed in guice-ext-annotations: https://github.com/xvik/dropwizard-guicey/issues/178. It supports both java 8 and java 11 (target API selected at runtime).
The library is already [released](https://github.com/xvik/guice-ext-annotations/releases/tag/1.4.0) so you can update dependency manually to fix this warning:

```
implementation 'ru.vyarus:guice-ext-annotations:1.4.0
```

(guicey with updated dependency was not released yet)

**Comment by mumeraltaf** [comment]
Thanks for the update, I can confirm when using 
`'ru.vyarus:guice-ext-annotations:1.4.0`

_guicey-jdbi3_ works with Java 16.
