### ISSUE TITLE
RedisRateLimiter bundle add

### ISSUE THREAD

**Issue by Karthik-Gupta** [xvik/dropwizard-guicey-examples#8]
Hi

I am trying to add a RateLimitBundle to by DW application.
For the actual scenario, I would like you to refer this below link:
https://github.com/mokies/ratelimitj/tree/master/ratelimitj-dropwizard

In this context, I need to input the redis host ("redis://localhost:7006") from application.yml, I do not want to hard code it.

Please let me know if there is any work around for this.

**Comment by xvik** [comment]
Hi!
It's not possible. You can only introduce an additional configuration file like redis.properties and read it manually (to use redis address from there).
